### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by MarioProjects** [taki0112/StarGAN_v2-Tensorflow#1]
Hi, first of all thanks for your amazing work! Could you provide some pretrained model? Thanks!

**Comment by lxy2017** [comment]
Hi, --num_style = 5,  which style did you use? Thanks!

**Comment by taki0112** [comment]
Since my code may be a little different from the author code, when the author releases the code, I will revise the code and open the pretrain model.

**Comment by gigadeplex** [comment]
> 
> 
> Since my code may be a little different from the author code, when the author releases the code, I will revise the code and open the pretrain model.

so one month has passed since the uathor released his code, where's the pretrained?

**Comment by gigadeplex** [comment]
> 
> 
> Since my code may be a little different from the author code, when the author releases the code, I will revise the code and open the pretrain model.

Hi, one month has passed since the authors released their code + model, so where's your pretrained model?
