### ISSUE TITLE
Style num

### ISSUE THREAD

**Issue by lxy2017** [taki0112/StarGAN_v2-Tensorflow#2]
Hi, --num_style = 5, which style did you use? Thanks!

**Comment by taki0112** [comment]
When phase is test, `num_style` means the number of randomly generated outputs.

**Comment by lxy2017** [comment]
thanks,  if num_style > 5  num_style may be 8 or 16 is better than 5?

**Comment by taki0112** [comment]
if num_style larger, then you will get the more variety of images.
But num_style is not related to performance.
